image: docker:19.03.12

services:
  - docker:19.03.12-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:server -f Dockerfile.server .
    - docker build -t $CI_REGISTRY_IMAGE:agent -f Dockerfile.agent .

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/server.yaml
    - kubectl apply -f k8s/agent.yaml
  only:
    - master
