apiVersion: v1
kind: Service
metadata:
  name: distributed-calculator
spec:
  selector:
    app: distributed-calculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
